<a href="https://colab.research.google.com/github/SyedQalbemohsin/Machine_learning-Projects/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [ ]:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time
start =time.time()
for i in range(len(a)):
 c.append(a[i]+b[i])
print(time.time()-start)

2.843430995941162


In [ ]:
#numpy
import time
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)


0.643052339553833


In [ ]:
#memory
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [ ]:
#lower memory
a = np.arange(10000000,dtype=np.int16)
sys.getsizeof(a)

20000112

In [ ]:
#normal indexing and slicing
import numpy as np
a = np.random.randint(1,24,100)
a

array([20, 23,  5,  5, 12, 22, 22, 21, 16,  2,  2,  8,  2, 13, 17, 23,  9,
       11,  7, 13,  8,  7,  6, 14,  6,  5, 19, 12, 14, 20, 11, 17, 14, 19,
       11, 16, 19,  4,  8, 18, 15,  7, 12,  1,  2, 10, 18,  9,  4, 23, 14,
       21, 17, 12, 22,  7, 12, 22, 17,  5, 22, 19, 23, 23, 13,  8,  9, 12,
       20, 22, 12, 21, 12, 14,  9,  2, 19,  2, 18, 10, 23, 18, 20, 16, 20,
        2, 16, 11,  9, 12, 14, 15, 10,  1,  2, 13,  9, 20, 21,  6])

In [ ]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[::2]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [ ]:
#fancy indexing
a[[0,2,3,5]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
#boolean indexing
np.random.randint(1,100,24).reshape(6,4)

array([[71, 33, 62, 61],
       [82, 22, 22, 93],
       [13, 44, 57, 85],
       [16, 83, 11, 36],
       [41, 77, 35, 78],
       [36, 30, 31, 97]])

In [ ]:
#find all numbers greater then 50 boolean
a>50

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#find all numbers less then 50
a[a < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#find even numbers
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
#find out numbers less then 50 and even
a[(a < 50) & (a % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
#find numbers divisible by 7
a[a % 7 == 0]

array([ 0,  7, 14, 21])

In [ ]:
#find numbers not divisible by 7
a[~(a % 7 == 0)]


array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19,
       20, 22, 23])

In [ ]:
# @title Broadcasting
#Broadcasting is a term describing how Numpy treats to different shapes of arrays during arithematic operation
# the smaller array is broadcasted to larger array so that they have compatible shapes

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [ ]:
# @title Broadcasting Rules
# 1. add 1 to the head of smaller array to make it same dimension like the larger array a[3,3,3] so if b[3] so make b[1,1,3]
# 2. then make 1 similar value the larger array have like b to [3,3,3]
# 3. error if there is no 1 dimension

In [ ]:
#example
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)
print(a+b)
#this work because added 1 to head of b then make it (4,3) then added

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
#example
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
print(a+b)
# we can only increase 1 to the value of larger array value
#this will not work because added 1 to head of b and the second value is 3 so we cant make it 4 in 1Dimension we make only first value to first value of larger array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
#example
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)
#this work because we only have to match both array values then added here because wwe are only increasing 1 not any other number

In [ ]:
#example
a = np.arange(4).reshape(2,2)
b = np.arange(1)
print(a)
print(b)
print(a+b)
#first 1 added to head of b then we increases 1 to the values of larger array

In [ ]:
#example
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)
print(a)
print(b)
print(a+b)
# error because we dont have 1 on either side to increase

In [ ]:
#sigmoid is a math function
def sigmoid(array):
  return 1/(1+np.exp(-(array)))

a = np.arange(10)
sigmoid(a)

In [ ]:
# @title Mean Squared Function
#mean square error is the difference of original value and the predicted value loss function of linear regression
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [ ]:
def mse(actual,predicted):
  return np.mean((actual-predicted)**2)

mse(actual,predicted)

In [ ]:
predicted

In [ ]:
actual

In [ ]:
# binary cross entropy
def bce()

In [ ]:
# @title Nan values
#working with missing values -> np.nan means no value
import numpy as np    # through this fucntion we can check unlimited nan and real values
a = np.array([1,2,np.nan,3,4,np.nan])
print(np.isnan(a))


In [ ]:
a[np.isnan(a)] #here we will get nan values

In [ ]:
a[~(np.isnan(a))] #here we applied not(~) operator so we will get real values

In [ ]:
# @title Plotting graph
#plotting a 2D plot
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
x
y=x
y
plt.plot(x,y)

In [ ]:
#y = x^2
x = np.linspace(-10,10,100)
y = x**2
plt.plot(x,y)

In [ ]:
# y=sin(x)

y =np.sin(x)
plt.plot(x,y)

In [ ]:
# y=cos(x)
y = np.cos(x)
plt.plot(x,y)

In [ ]:
# y=xlogx
y=x*np.log(x)
plt.plot(x,y)

In [ ]:
#sigmoid graph
y = 1/(1+np.exp(-(x)))
plt.plot(x,y)

In [ ]:
import numpy as np
a = np.random.randint(1,100,15) #1D array
a

In [ ]:
np.sort(a)

In [ ]:
np.sort(a)[::-1] #for descending sort

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

In [ ]:
np.sort(b,axis=1) #sort column wise

In [ ]:
np.sort(b,axis=0) #sort row wise

In [ ]:
# @title Append Function
b = np.random.randint(1,100,24)
np.append(b,100)


In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b


In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

In [ ]:
# @title Concatenate Function
b = np.random.randint(1,100,16).reshape(4,4)
c = np.random.randint(1,50,16).reshape(4,4)
np.concatenate((b,c),axis=1)



In [ ]:
b = np.random.randint(1,100,16).reshape(4,4)
c = np.random.randint(1,50,16).reshape(4,4)
np.concatenate((b,c),axis=0)


In [ ]:
# @title Unique Function
#can be used in machine learning to increase inputs
b = np.array([1,1,2,2,3,3,4])
np.unique(b)

In [ ]:
# @title Expand Dimension
b


In [ ]:
np.expand_dims(b,axis=1)

In [ ]:
b.shape

In [ ]:
# @title Where function
# np.where() return the indies of an element in an input where the given condition is satisfied
a = np.random.randint(30,100,10)
a


In [ ]:
# find index of elements >50
np.where(a>50)

In [ ]:
#replace all values >50 with 0
#np.where(condition,true,false)
np.where(a>50,0,a)

In [ ]:
#replace even numbers with 0
np.where(a%2==0,0,a)

In [ ]:
# @title Argmax function
np.argmax(a)


In [ ]:
#2d argmax
b = np.random.randint(1,100,16).reshape(4,4)
np.argmax(b,axis=0)

In [ ]:
# @title Argmin function
np.argmin(a)


In [ ]:
#2d argmin
b = np.random.randint(1,100,16).reshape(4,4)


In [ ]:
np.argmin(b,axis=0)

In [ ]:
# @title Cummulative Sum
np.cumsum(a)

In [ ]:
#for 2D array
#column wise
b
np.cumsum(b,axis=0)

In [ ]:
np.cumprod(b,axis=1)
#row wise axis=1,for column axis=0

In [ ]:
# @title Percentile function
# 100 will show the max value
# 50 will show median value
#0 will show max value
# formula is (n/N)*100

In [ ]:
a = np.random.randint(30,100,10)
a


In [ ]:
np.percentile(a,100) #max value nearby 100

np.float64(91.0)

In [ ]:
np.percentile(a,50)

np.float64(57.0)

In [ ]:
np.percentile(a,0)

np.float64(37.0)

In [ ]:
# @title Histogram
#this will returns the value of the elements in a mentioned range
#like below from 0-50 there is 3 elements and from 50-100 there is 7 elements
np.histogram(a,bins=[0,50,100])

(array([4, 6]), array([  0,  50, 100]))

In [ ]:
#@title Correlation Coefficients
# correlation of quantities
#if ans=1 means both are directly proportional
#if ans=0 no relation
#if ans= -1 means both are inversely proportional




In [ ]:
salary = np.array([100,200,300,400,500])
experience = np.array([1,2,3,2,4])
np.corrcoef(salary,experience)
#so here salary and experience are positively correlated
#here we have two quantities so output is 2*2

array([[1.        , 0.83205029],
       [0.83205029, 1.        ]])

In [ ]:
#@title Isin function
#will shows that how many values same are present in two different array
a

array([87, 74, 56, 75, 49, 37, 58, 47, 91, 41])

In [ ]:
items = np.array([33,2,120,58,40,30,20,10])
np.isin(a,items)


array([False, False, False, False, False, False,  True, False, False,
       False])

In [ ]:
 #to check same items in both arrays
 a [np.isin(a,items)]

array([58])

In [ ]:
#@title Flip
#reverses the order of the elements in array
a

array([87, 74, 56, 75, 49, 37, 58, 47, 91, 41])

In [ ]:
np.flip(a)

array([41, 91, 47, 58, 37, 49, 75, 56, 74, 87])

In [ ]:
np.flip(b)

array([2, 1, 0])

In [ ]:
# @title Put
# replaces the value from an array to given value
np.put(a,[0,1],[110,220])
a

array([110, 220,  56,  75,  49,  37,  58,  47,  91,  41])

In [ ]:
#@title Delete
#will delete single or multiple items
np.delete(a,[4,5])

array([110, 220,  56,  75,  58,  47,  91,  41])

In [ ]:
#@title Set Functions
#Union
m = np.array([1,2,3,4,5,6,7])
n = np.array([1,3,5,2,7,9,11])
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11])

In [ ]:
#Intersection
np.intersect1d(m,n)

array([1, 2, 3, 5, 7])

In [ ]:
# Set difference #items present in a not b
np.setdiff1d(m,n)

array([4, 6])

In [ ]:
#Setxor1d #non common of both
np.setxor1d(m,n)

array([ 4,  6,  9, 11])

In [ ]:
#In #checks that value is present or not
np.in1d(m,10)

/tmp/ipython-input-3212515312.py:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,10)


array([False, False, False, False, False, False, False])

In [ ]:
#@title Clip
#we makes a max and min limit and the values above and below it will be replaces by them
np.clip(a,a_max=75,a_min=25)

array([75, 75, 56, 75, 49, 37, 58, 47, 75, 41])